version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: api_certificados
    restart: unless-stopped
    environment:
      # --- AQUI ESTÁ A CONEXÃO CERTA (Copiada do seu .env) ---
      # Usamos aspas para garantir que os caracteres especiais não quebrem
      DATABASE_URL: "postgresql://fagsu:HMG_KA%23ueImgg%21LsLaH4%21%21@172.235.134.189:5432/fagsu?schema=public"
      
      PORT: 4000
      JWT_SECRET: "troque-este-segredo"
      
      # Mantemos '*' ou o domínio HTTPS para não bloquear o acesso do site
      FRONTEND_URL: "*"
    networks:
      - certificados-net
      - fag_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=fag_network"
      - "traefik.http.routers.api-certificados.rule=Host(`api-certificados.faculdadeguerra.edu.br`)"
      - "traefik.http.routers.api-certificados.entrypoints=websecure"
      - "traefik.http.routers.api-certificados.tls=true"
      - "traefik.http.routers.api-certificados.tls.certresolver=lets-encrypt"
      - "traefik.http.services.api-certificados.loadbalancer.server.port=4000"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=https://api-certificados.faculdadeguerra.edu.br
    container_name: web_certificados
    depends_on:
      - backend
    networks:
      - certificados-net
      - fag_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=fag_network"
      - "traefik.http.routers.web-certificados.rule=Host(`certificados.faculdadeguerra.edu.br`)"
      - "traefik.http.routers.web-certificados.entrypoints=websecure"
      - "traefik.http.routers.web-certificados.tls=true"
      - "traefik.http.routers.web-certificados.tls.certresolver=lets-encrypt"
      - "traefik.http.services.web-certificados.loadbalancer.server.port=80"

networks:
  certificados-net:
    driver: bridge
  fag_network:
    external: true