version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: api_certificados
    restart: unless-stopped
    environment:
      # Agora pegamos a URL completa direto do Portainer
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "4000:4000"
    networks:
      - certificados-net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: web_certificados
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - certificados-net

networks:
  certificados-net: