version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: api_certificados
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: https://certificados.faculdadeguerra.edu.br
    networks:
      - certificados-net
      - fag_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=fag_network"
      - "traefik.http.routers.api-certificados.rule=Host(`api-certificados.faculdadeguerra.edu.br`)"
      - "traefik.http.routers.api-certificados.entrypoints=websecure"
      - "traefik.http.routers.api-certificados.tls=true"
      - "traefik.http.routers.api-certificados.tls.certresolver=lets-encrypt"
      - "traefik.http.services.api-certificados.loadbalancer.server.port=4000"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=https://api-certificados.faculdadeguerra.edu.br
    container_name: web_certificados
    depends_on:
      - backend
    networks:
      - certificados-net
      - fag_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=fag_network"
      - "traefik.http.routers.web-certificados.rule=Host(`certificados.faculdadeguerra.edu.br`)"
      - "traefik.http.routers.web-certificados.entrypoints=websecure"
      - "traefik.http.routers.web-certificados.tls=true"
      - "traefik.http.routers.web-certificados.tls.certresolver=lets-encrypt"
      - "traefik.http.services.web-certificados.loadbalancer.server.port=80"

networks:
  certificados-net:
    driver: bridge

  fag_network:
    external: true
