apiVersion: v1
kind: Secret
metadata:
  name: certificados-backend-env
type: Opaque
stringData:
  NODE_ENV: production
  PORT: "4000"
  DATABASE_URL: postgresql://user:password@postgres:5432/certificados?schema=public
  JWT_SECRET: troque-este-segredo
  JWT_EXPIRES_IN: 2h
  BCRYPT_SALT_ROUNDS: "12"
  FRONTEND_URL: https://certificados.seudominio.com
  ADMIN_EMAIL: admin@certificados.com
  ADMIN_PASSWORD: Admin@123
