apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificados-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: certificados-frontend
  template:
    metadata:
      labels:
        app: certificados-frontend
    spec:
      containers:
        - name: web
          image: <FRONTEND_IMAGE_TAG>
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: certificados-frontend
spec:
  selector:
    app: certificados-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
